POST http://localhost:3000/user/register
Content-Type: application/json

{
    "firstname": "annan",
    "lastname": "annan",
    "email": "annan1@gmail.com",
    "password": "qwerty123"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "annan1@gmail.com",
    "password": "qwerty123"
}
